-- (1) Create copies of the IST302.PROMOTIONS, IST302.CUSTOMERS, IST302.CHANNELS, IST302.TIMES 
-- tables in your database 

SELECT * INTO MY_PROMOTIONS FROM IST302.dbo.PROMOTIONS
SELECT * INTO MY_CUSTOMERS FROM IST302.dbo.CUSTOMERS
SELECT * INTO MY_CHANNELS FROM IST302.dbo.CHANNELS
SELECT * INTO MY_TIMES FROM IST302.dbo.TIMES
SELECT * INTO MY_PRODUCTS_CE7 FROM IST302.dbo.PRODUCTS

-- Plan Type 1
CREATE INDEX IDX_SALES_CUST_ID ON MY_SALES(CUST_ID)
CREATE INDEX IDX_SALES_PROD_ID ON MY_SALES(PROD_ID)
CREATE INDEX IDX_SALES_PROMO_ID ON MY_SALES(PROMO_ID)
CREATE INDEX IDX_SALES_CHANNEL_ID ON MY_SALES(CHANNEL_ID)
CREATE INDEX IDX_SALES_TIME_ID ON MY_SALES(TIME_ID)
CREATE INDEX IDX_PROMO_ID ON MY_PROMOTIONS(PROMO_ID)
CREATE INDEX IDX_CUST_ID ON MY_CUSTOMERS(CUST_ID)
CREATE INDEX IDX_CHANNEL_ID ON MY_CHANNELS(CHANNEL_ID)
CREATE INDEX IDX_TIME_ID ON MY_TIMES(TIME_ID)
CREATE INDEX IDX_PROD_ID ON MY_PRODUCTS_CE7(PROD_ID)

-- Plan Type 1 Q.a
SET SHOWPLAN_TEXT ON
SELECT
	CUST_LAST_NAME + ', ' + CUST_FIRST_NAME AS CUST_NAME,
	FISCAL_MONTH_NAME, S.TIME_ID AS SALES_DATE, CHANNEL_DESC,
	PROMO_NAME, PROD_SUBCATEGORY, PROD_NAME, AMOUNT_SOLD
FROM MY_SALES S
INNER JOIN MY_CUSTOMERS C
	ON S.CUST_ID = C.CUST_ID
INNER JOIN MY_PRODUCTS_CE7 P
	ON S.PROD_ID = P.PROD_ID
INNER JOIN MY_PROMOTIONS R
	ON S.PROMO_ID = R.PROMO_ID
INNER JOIN MY_CHANNELS H
	ON S.CHANNEL_ID = H.CHANNEL_ID
INNER JOIN MY_TIMES T
	ON S.TIME_ID = T.TIME_ID
WHERE CUST_GENDER = 'M' AND CUST_MARITAL_STATUS = 'Married'
	AND FISCAL_MONTH_NAME IN ('February', 'March', 'April', 'May', 'June')
	AND PROD_SUBCATEGORY IN ('Monitors', 'Recordable CDs')
	AND CHANNEL_DESC = 'Tele Sales'
	AND S.TIME_ID BETWEEN '02-25-1998' AND '01-30-2000';	
GO
SET SHOWPLAN_TEXT OFF

-- Plan Type 1 Q.b
SET SHOWPLAN_TEXT ON
SELECT
	CUST_LAST_NAME + ', ' + CUST_FIRST_NAME AS CUST_NAME
FROM
	MY_SALES S
INNER JOIN MY_CUSTOMERS C
	ON S.CUST_ID = C.CUST_ID
INNER JOIN MY_PRODUCTS_CE7 P
	ON S.PROD_ID = P.PROD_ID
INNER JOIN MY_PROMOTIONS R
	ON S.PROMO_ID = R.PROMO_ID
INNER JOIN MY_CHANNELS H
	ON S.CHANNEL_ID = H.CHANNEL_ID
INNER JOIN MY_TIMES T
	ON S.TIME_ID = T.TIME_ID
WHERE CUST_GENDER = 'M' AND CUST_MARITAL_STATUS = 'Married'
	AND PROD_SUBCATEGORY IN ('Monitors', 'Recordable CDs')
EXCEPT
SELECT
	CUST_LAST_NAME + ', ' + CUST_FIRST_NAME AS CUST_NAME
FROM
	MY_SALES S
INNER JOIN MY_CUSTOMERS C
	ON S.CUST_ID = C.CUST_ID
INNER JOIN MY_PRODUCTS_CE7 P
	ON S.PROD_ID = P.PROD_ID
INNER JOIN MY_PROMOTIONS R
	ON S.PROMO_ID = R.PROMO_ID
INNER JOIN MY_CHANNELS H
	ON S.CHANNEL_ID = H.CHANNEL_ID
INNER JOIN MY_TIMES T
	ON S.TIME_ID = T.TIME_ID
WHERE FISCAL_MONTH_NAME IN ('February', 'March', 'April', 'May', 'June')
	AND CHANNEL_DESC = 'Direct Sales'
	AND S.TIME_ID BETWEEN '02-25-1998' AND '01-30-2000';

SET SHOWPLAN_TEXT OFF

-- Plan Type 1 Q.c
SET SHOWPLAN_TEXT ON
SELECT
	CUST_GENDER AS GENDER, PROD_SUBCATEGORY,
	FISCAL_MONTH_NAME, MONTH(S.TIME_ID) AS SALES_MONTH,
	CHANNEL_CLASS,SUM(AMOUNT_SOLD) AS TOTAL_AMOUNT_SOLD
FROM
	MY_SALES S
INNER JOIN MY_CUSTOMERS C
	ON S.CUST_ID = C.CUST_ID
INNER JOIN MY_PRODUCTS_CE7 P
	ON S.PROD_ID = P.PROD_ID
INNER JOIN MY_PROMOTIONS R
	ON S.PROMO_ID = R.PROMO_ID
INNER JOIN MY_CHANNELS H
ON S.CHANNEL_ID = H.CHANNEL_ID
INNER JOIN MY_TIMES T
	ON S.TIME_ID = T.TIME_ID
WHERE CUST_GENDER = 'M' AND CUST_MARITAL_STATUS = 'Married'
	AND FISCAL_MONTH_NAME IN ('February', 'March', 'April', 'May', 'June')
	AND PROD_SUBCATEGORY IN ('Monitors', 'Recordable CDs')
	AND S.TIME_ID BETWEEN '02-25-1998' AND '01-30-2000'
GROUP BY
	CUST_GENDER, PROD_SUBCATEGORY, FISCAL_MONTH_NAME,
	MONTH(S.TIME_ID), CHANNEL_CLASS;

SET SHOWPLAN_TEXT OFF

-- Plan Type 2
CREATE INDEX IDX_CUST_GEN ON MY_CUSTOMERS(CUST_GENDER)
CREATE INDEX IDX_CUST_MAR ON MY_CUSTOMERS(CUST_MARITAL_STATUS)
CREATE INDEX IDX_FIS_MONTH ON MY_TIMES(FISCAL_MONTH_NAME)
CREATE INDEX IDX_PROD_SUBC ON MY_PRODUCTS_CE7(PROD_SUBCATEGORY)
CREATE INDEX IDX_CHANNEL_DESC ON MY_CHANNELS(CHANNEL_DESC)
CREATE INDEX IDX_TIME ON MY_SALES(TIME_ID)

DROP INDEX IDX_CUST_GEN ON MY_CUSTOMERS
DROP INDEX IDX_CUST_MAR ON MY_CUSTOMERS
DROP INDEX IDX_FIS_MONTH ON MY_TIMES
DROP INDEX IDX_PROD_SUBC ON MY_PRODUCTS_CE7
DROP INDEX IDX_CHANNEL_DESC ON MY_CHANNELS
DROP INDEX IDX_TIME ON MY_SALES

-- Plan Type 2 Q.a
SET SHOWPLAN_TEXT ON
SELECT
	CUST_LAST_NAME + ', ' + CUST_FIRST_NAME AS CUST_NAME,
	FISCAL_MONTH_NAME, S.TIME_ID AS SALES_DATE, CHANNEL_DESC,
	PROMO_NAME, PROD_SUBCATEGORY, PROD_NAME, AMOUNT_SOLD
FROM MY_SALES S
INNER JOIN MY_CUSTOMERS C
	ON S.CUST_ID = C.CUST_ID
INNER JOIN MY_PRODUCTS_CE7 P
	ON S.PROD_ID = P.PROD_ID
INNER JOIN MY_PROMOTIONS R
	ON S.PROMO_ID = R.PROMO_ID
INNER JOIN MY_CHANNELS H
	ON S.CHANNEL_ID = H.CHANNEL_ID
INNER JOIN MY_TIMES T
	ON S.TIME_ID = T.TIME_ID
WHERE CUST_GENDER = 'M' AND CUST_MARITAL_STATUS = 'Married'
	AND FISCAL_MONTH_NAME IN ('February', 'March', 'April', 'May', 'June')
	AND PROD_SUBCATEGORY IN ('Monitors', 'Recordable CDs')
	AND CHANNEL_DESC = 'Tele Sales'
	AND S.TIME_ID BETWEEN '02-25-1998' AND '01-30-2000';	
GO

SET SHOWPLAN_TEXT OFF

-- Plan Type 2 Q.b
SET SHOWPLAN_TEXT ON
SELECT
	CUST_LAST_NAME + ', ' + CUST_FIRST_NAME AS CUST_NAME
FROM
	MY_SALES S
INNER JOIN MY_CUSTOMERS C
	ON S.CUST_ID = C.CUST_ID
INNER JOIN MY_PRODUCTS_CE7 P
	ON S.PROD_ID = P.PROD_ID
INNER JOIN MY_PROMOTIONS R
	ON S.PROMO_ID = R.PROMO_ID
INNER JOIN MY_CHANNELS H
	ON S.CHANNEL_ID = H.CHANNEL_ID
INNER JOIN MY_TIMES T
	ON S.TIME_ID = T.TIME_ID
WHERE CUST_GENDER = 'M' AND CUST_MARITAL_STATUS = 'Married'
	AND PROD_SUBCATEGORY IN ('Monitors', 'Recordable CDs')
EXCEPT
SELECT
	CUST_LAST_NAME + ', ' + CUST_FIRST_NAME AS CUST_NAME
FROM
	MY_SALES S
INNER JOIN MY_CUSTOMERS C
	ON S.CUST_ID = C.CUST_ID
INNER JOIN MY_PRODUCTS_CE7 P
	ON S.PROD_ID = P.PROD_ID
INNER JOIN MY_PROMOTIONS R
	ON S.PROMO_ID = R.PROMO_ID
INNER JOIN MY_CHANNELS H
	ON S.CHANNEL_ID = H.CHANNEL_ID
INNER JOIN MY_TIMES T
	ON S.TIME_ID = T.TIME_ID
WHERE FISCAL_MONTH_NAME IN ('February', 'March', 'April', 'May', 'June')
	AND CHANNEL_DESC = 'Direct Sales'
	AND S.TIME_ID BETWEEN '02-25-1998' AND '01-30-2000';
SET SHOWPLAN_TEXT OFF

-- Plan Type 2 Q.c
SET SHOWPLAN_TEXT ON
SELECT
	CUST_GENDER AS GENDER, PROD_SUBCATEGORY,
	FISCAL_MONTH_NAME, MONTH(S.TIME_ID) AS SALES_MONTH,
	CHANNEL_CLASS,SUM(AMOUNT_SOLD) AS TOTAL_AMOUNT_SOLD
FROM
	MY_SALES S
INNER JOIN MY_CUSTOMERS C
	ON S.CUST_ID = C.CUST_ID
INNER JOIN MY_PRODUCTS_CE7 P
	ON S.PROD_ID = P.PROD_ID
INNER JOIN MY_PROMOTIONS R
	ON S.PROMO_ID = R.PROMO_ID
INNER JOIN MY_CHANNELS H
ON S.CHANNEL_ID = H.CHANNEL_ID
INNER JOIN MY_TIMES T
	ON S.TIME_ID = T.TIME_ID
WHERE CUST_GENDER = 'M' AND CUST_MARITAL_STATUS = 'Married'
	AND FISCAL_MONTH_NAME IN ('February', 'March', 'April', 'May', 'June')
	AND PROD_SUBCATEGORY IN ('Monitors', 'Recordable CDs')
	AND S.TIME_ID BETWEEN '02-25-1998' AND '01-30-2000'
GROUP BY
	CUST_GENDER, PROD_SUBCATEGORY, FISCAL_MONTH_NAME,
	MONTH(S.TIME_ID), CHANNEL_CLASS;

SET SHOWPLAN_TEXT OFF


-- Plan Type 4
CREATE INDEX IDX_CUST_GEN_MAR ON MY_CUSTOMERS(CUST_GENDER, CUST_MARITAL_STATUS)
DROP INDEX IDX_CUST_GEN_MAR ON MY_CUSTOMERS
-- Plan Type 4 Q.a
SET SHOWPLAN_TEXT ON
SELECT
	CUST_LAST_NAME + ', ' + CUST_FIRST_NAME AS CUST_NAME,
	FISCAL_MONTH_NAME, S.TIME_ID AS SALES_DATE, CHANNEL_DESC,
	PROMO_NAME, PROD_SUBCATEGORY, PROD_NAME, AMOUNT_SOLD
FROM MY_SALES S
INNER JOIN MY_CUSTOMERS C
	ON S.CUST_ID = C.CUST_ID
INNER JOIN MY_PRODUCTS_CE7 P
	ON S.PROD_ID = P.PROD_ID
INNER JOIN MY_PROMOTIONS R
	ON S.PROMO_ID = R.PROMO_ID
INNER JOIN MY_CHANNELS H
	ON S.CHANNEL_ID = H.CHANNEL_ID
INNER JOIN MY_TIMES T
	ON S.TIME_ID = T.TIME_ID
WHERE CUST_GENDER = 'M' AND CUST_MARITAL_STATUS = 'Married'
	AND FISCAL_MONTH_NAME IN ('February', 'March', 'April', 'May', 'June')
	AND PROD_SUBCATEGORY IN ('Monitors', 'Recordable CDs')
	AND CHANNEL_DESC = 'Tele Sales'
	AND S.TIME_ID BETWEEN '02-25-1998' AND '01-30-2000';	
GO

SET SHOWPLAN_TEXT OFF

-- Plan Type 4 Q.b
SET SHOWPLAN_TEXT ON
SELECT
	CUST_LAST_NAME + ', ' + CUST_FIRST_NAME AS CUST_NAME
FROM
	MY_SALES S
INNER JOIN MY_CUSTOMERS C
	ON S.CUST_ID = C.CUST_ID
INNER JOIN MY_PRODUCTS_CE7 P
	ON S.PROD_ID = P.PROD_ID
INNER JOIN MY_PROMOTIONS R
	ON S.PROMO_ID = R.PROMO_ID
INNER JOIN MY_CHANNELS H
	ON S.CHANNEL_ID = H.CHANNEL_ID
INNER JOIN MY_TIMES T
	ON S.TIME_ID = T.TIME_ID
WHERE CUST_GENDER = 'M' AND CUST_MARITAL_STATUS = 'Married'
	AND PROD_SUBCATEGORY IN ('Monitors', 'Recordable CDs')
EXCEPT
SELECT
	CUST_LAST_NAME + ', ' + CUST_FIRST_NAME AS CUST_NAME
FROM
	MY_SALES S
INNER JOIN MY_CUSTOMERS C
	ON S.CUST_ID = C.CUST_ID
INNER JOIN MY_PRODUCTS_CE7 P
	ON S.PROD_ID = P.PROD_ID
INNER JOIN MY_PROMOTIONS R
	ON S.PROMO_ID = R.PROMO_ID
INNER JOIN MY_CHANNELS H
	ON S.CHANNEL_ID = H.CHANNEL_ID
INNER JOIN MY_TIMES T
	ON S.TIME_ID = T.TIME_ID
WHERE FISCAL_MONTH_NAME IN ('February', 'March', 'April', 'May', 'June')
	AND CHANNEL_DESC = 'Direct Sales'
	AND S.TIME_ID BETWEEN '02-25-1998' AND '01-30-2000';
SET SHOWPLAN_TEXT OFF

-- Plan Type 4 Q.c
SET SHOWPLAN_TEXT ON
SELECT
	CUST_GENDER AS GENDER, PROD_SUBCATEGORY,
	FISCAL_MONTH_NAME, MONTH(S.TIME_ID) AS SALES_MONTH,
	CHANNEL_CLASS,SUM(AMOUNT_SOLD) AS TOTAL_AMOUNT_SOLD
FROM
	MY_SALES S
INNER JOIN MY_CUSTOMERS C
	ON S.CUST_ID = C.CUST_ID
INNER JOIN MY_PRODUCTS_CE7 P
	ON S.PROD_ID = P.PROD_ID
INNER JOIN MY_PROMOTIONS R
	ON S.PROMO_ID = R.PROMO_ID
INNER JOIN MY_CHANNELS H
ON S.CHANNEL_ID = H.CHANNEL_ID
INNER JOIN MY_TIMES T
	ON S.TIME_ID = T.TIME_ID
WHERE CUST_GENDER = 'M' AND CUST_MARITAL_STATUS = 'Married'
	AND FISCAL_MONTH_NAME IN ('February', 'March', 'April', 'May', 'June')
	AND PROD_SUBCATEGORY IN ('Monitors', 'Recordable CDs')
	AND S.TIME_ID BETWEEN '02-25-1998' AND '01-30-2000'
GROUP BY
	CUST_GENDER, PROD_SUBCATEGORY, FISCAL_MONTH_NAME,
	MONTH(S.TIME_ID), CHANNEL_CLASS;

SET SHOWPLAN_TEXT OFF

-- Plan Type 3 Q.a
SET SHOWPLAN_TEXT ON
SELECT
	CUST_LAST_NAME + ', ' + CUST_FIRST_NAME AS CUST_NAME,
	FISCAL_MONTH_NAME, S.TIME_ID AS SALES_DATE, CHANNEL_DESC,
	PROMO_NAME, PROD_SUBCATEGORY, PROD_NAME, AMOUNT_SOLD
FROM MY_SALES S
WITH (INDEX(IDX_SALES_CUST_ID))
INNER JOIN MY_CUSTOMERS C
	ON S.CUST_ID = C.CUST_ID
INNER JOIN MY_PRODUCTS_CE7 P
	ON S.PROD_ID = P.PROD_ID
INNER JOIN MY_PROMOTIONS R
	ON S.PROMO_ID = R.PROMO_ID
INNER JOIN MY_CHANNELS H
	ON S.CHANNEL_ID = H.CHANNEL_ID
INNER JOIN MY_TIMES T
	ON S.TIME_ID = T.TIME_ID
WHERE CUST_GENDER = 'M' AND CUST_MARITAL_STATUS = 'Married'
	AND FISCAL_MONTH_NAME IN ('February', 'March', 'April', 'May', 'June')
	AND PROD_SUBCATEGORY IN ('Monitors', 'Recordable CDs')
	AND CHANNEL_DESC = 'Tele Sales'
	AND S.TIME_ID BETWEEN '02-25-1998' AND '01-30-2000';	
GO

SET SHOWPLAN_TEXT OFF

-- Plan Type 3 Q.b
SET SHOWPLAN_TEXT ON
SELECT
	CUST_LAST_NAME + ', ' + CUST_FIRST_NAME AS CUST_NAME
FROM
	MY_SALES S
WITH (INDEX(IDX_SALES_CUST_ID))
INNER JOIN MY_CUSTOMERS C
	ON S.CUST_ID = C.CUST_ID
INNER JOIN MY_PRODUCTS_CE7 P
	ON S.PROD_ID = P.PROD_ID
INNER JOIN MY_PROMOTIONS R
	ON S.PROMO_ID = R.PROMO_ID
INNER JOIN MY_CHANNELS H
	ON S.CHANNEL_ID = H.CHANNEL_ID
INNER JOIN MY_TIMES T
	ON S.TIME_ID = T.TIME_ID
WHERE CUST_GENDER = 'M' AND CUST_MARITAL_STATUS = 'Married'
	AND PROD_SUBCATEGORY IN ('Monitors', 'Recordable CDs')
EXCEPT
SELECT
	CUST_LAST_NAME + ', ' + CUST_FIRST_NAME AS CUST_NAME
FROM
	MY_SALES S
INNER JOIN MY_CUSTOMERS C
	ON S.CUST_ID = C.CUST_ID
INNER JOIN MY_PRODUCTS_CE7 P
	ON S.PROD_ID = P.PROD_ID
INNER JOIN MY_PROMOTIONS R
	ON S.PROMO_ID = R.PROMO_ID
INNER JOIN MY_CHANNELS H
	ON S.CHANNEL_ID = H.CHANNEL_ID
INNER JOIN MY_TIMES T
	ON S.TIME_ID = T.TIME_ID
WHERE FISCAL_MONTH_NAME IN ('February', 'March', 'April', 'May', 'June')
	AND CHANNEL_DESC = 'Direct Sales'
	AND S.TIME_ID BETWEEN '02-25-1998' AND '01-30-2000';
SET SHOWPLAN_TEXT OFF

-- Plan Type 3 Q.c
SET SHOWPLAN_TEXT ON
SELECT
	CUST_GENDER AS GENDER, PROD_SUBCATEGORY,
	FISCAL_MONTH_NAME, MONTH(S.TIME_ID) AS SALES_MONTH,
	CHANNEL_CLASS,SUM(AMOUNT_SOLD) AS TOTAL_AMOUNT_SOLD
FROM
	MY_SALES S
WITH (INDEX(IDX_SALES_CUST_ID))
INNER JOIN MY_CUSTOMERS C
	ON S.CUST_ID = C.CUST_ID
INNER JOIN MY_PRODUCTS_CE7 P
	ON S.PROD_ID = P.PROD_ID
INNER JOIN MY_PROMOTIONS R
	ON S.PROMO_ID = R.PROMO_ID
INNER JOIN MY_CHANNELS H
ON S.CHANNEL_ID = H.CHANNEL_ID
INNER JOIN MY_TIMES T
	ON S.TIME_ID = T.TIME_ID
WHERE CUST_GENDER = 'M' AND CUST_MARITAL_STATUS = 'Married'
	AND FISCAL_MONTH_NAME IN ('February', 'March', 'April', 'May', 'June')
	AND PROD_SUBCATEGORY IN ('Monitors', 'Recordable CDs')
	AND S.TIME_ID BETWEEN '02-25-1998' AND '01-30-2000'
GROUP BY
	CUST_GENDER, PROD_SUBCATEGORY, FISCAL_MONTH_NAME,
	MONTH(S.TIME_ID), CHANNEL_CLASS;

SET SHOWPLAN_TEXT OFF

