CREATE VIEW [PE9_UPDATE] AS
SELECT PROD_NAME, PROD_CATEGORY
FROM MY_PRODUCTS
WHERE PROD_CATEGORY IN ('Peripherals and Accessories', 'Photo')



SELECT * FROM MY_PRODUCTS

GRANT INSERT ON MY_PRODUCTS TO MOJA
INSERT INTO MY_PRODUCTS
VALUES (150, 'Test Product', 'Electronics', 'Electronics', 'STATUS', 500, 500)


CREATE VIEW MY_PRODUCTS_UPDATE_MOYA AS
SELECT PROD_NAME, PROD_CATEGORY
FROM MY_PRODUCTS
WHERE PROD_CATEGORY IN ('Peripherals and Accessories', 'Photo')
WITH CHECK OPTION


UPDATE MY_PRODUCTS_UPDATE_MOYA
SET PROD_STATUS = 'Test'
WHERE PROD_CATEGORY = 'Photo'

DELETE FROM MY_PRODUCTS WHERE PROD_CATEGORY = 'Photo'


CREATE VIEW MY_PRODUCTS_SELECT_MOYA AS
SELECT PROD_NAME, PROD_CATEGORY
FROM MY_PRODUCTS
WHERE PROD_LIST_PRICE < (
SELECT AVG(PROD_LIST_PRICE)
FROM MY_PRODUCTS
)
