-- Question 1 (a) 

CREATE TABLE MY_PRODUCTS
(
	PROD_ID int NOT NULL,
	PROD_NAME varchar(50) NOT NULL,
	PROD_CATEGORY varchar(50) NOT NULL,
    PROD_CAT_DESC varchar(2000) NOT NULL,
    PROD_STATUS varchar(20) NOT NULL,
    PROD_LIST_PRICE decimal(8, 2) NOT NULL,
    PROD_MIN_PRICE decimal(8, 2) NOT NULL

)

-- Question 1 (b)

INSERT INTO MY_PRODUCTS
SELECT PROD_ID
    , PROD_NAME
    , PROD_CATEGORY
    , PROD_CAT_DESC
    , PROD_STATUS
    , PROD_LIST_PRICE
    , PROD_MIN_PRICE
FROM IST302.dbo.PRODUCTS

SELECT * FROM MY_PRODUCTS


-- Question 2 (a)
CREATE CLUSTERED INDEX IDX_PROD_ID ON MY_PRODUCTS (PROD_ID)
WITH (FILLFACTOR  = 90); 

-- Question 2 (b)
CREATE INDEX IDX_PROD_CATEGORY ON MY_PRODUCTS (PROD_CATEGORY);


